languageCode = "en-us"
title = "Migration UI"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
baseUrl = "/"

disableKinds = ["taxonomy","taxonomyTerm"]

[params]
	description = "Migration UI"

	logo = "images/asset-hub.svg"
	favicon = "/images/asset-hub.png"

[params.palette]
    primary = "grey"
    accent  = "teal"

[params.font]
    text = "Roboto"
    code = "Roboto Mono"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true


[[menu.main]]
	name   = "Introduction"
	url    = "/"
	weight = 10
[[menu.main]]
	name   = "Migration UI"
	url    = "/"
	weight = 20
[[menu.main]]
	name   = "Che Web IDE"
	url    = "/"
	weight = 30
[[menu.main]]
	name   = "Migrate Job"
	url    = "/"
	weight = 40
[[menu.main]]
    name   = "Build and Run"
    url    = "buildandrun/"
    weight = 100
